/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BasicInfo } from '../models';
// @ts-ignore
import type { UpdateResponse } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/profile/basic-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoPut: async (basicInfo: BasicInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'basicInfo' is not null or undefined
            assertParamExists('apiProfileBasicInfoPut', 'basicInfo', basicInfo)
            const localVarPath = `/api/profile/basic-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(basicInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProfileBasicInfoGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BasicInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiProfileBasicInfoGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiProfileBasicInfoGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiProfileBasicInfoPut(basicInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiProfileBasicInfoPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 現在登録されているユーザーの基本情報を返します。
         * @summary 基本情報を取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoGet(options?: RawAxiosRequestConfig): AxiosPromise<BasicInfo> {
            return localVarFp.apiProfileBasicInfoGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 学籍番号や名前、自己紹介などの基本情報を編集します。
         * @summary 基本情報を更新する
         * @param {BasicInfo} basicInfo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig): AxiosPromise<UpdateResponse> {
            return localVarFp.apiProfileBasicInfoPut(basicInfo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 現在登録されているユーザーの基本情報を返します。
     * @summary 基本情報を取得する
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiProfileBasicInfoGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiProfileBasicInfoGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 学籍番号や名前、自己紹介などの基本情報を編集します。
     * @summary 基本情報を更新する
     * @param {BasicInfo} basicInfo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiProfileBasicInfoPut(basicInfo: BasicInfo, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiProfileBasicInfoPut(basicInfo, options).then((request) => request(this.axios, this.basePath));
    }
}

