/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiProfileBasicInfoPut200Response
 */
export interface ApiProfileBasicInfoPut200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiProfileBasicInfoPut200Response
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProfileBasicInfoPut200Response
     */
    'message'?: string;
}

