/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Visibility } from './visibility';

/**
 * 
 * @export
 * @interface BasicInfo
 */
export interface BasicInfo {
    /**
     * 
     * @type {string}
     * @memberof BasicInfo
     */
    'student_id': string;
    /**
     * 
     * @type {string}
     * @memberof BasicInfo
     */
    'faculty': string;
    /**
     * 
     * @type {string}
     * @memberof BasicInfo
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof BasicInfo
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof BasicInfo
     */
    'nickname': string;
    /**
     * Markdown形式の自己紹介文
     * @type {string}
     * @memberof BasicInfo
     */
    'self_introduction': string;
    /**
     * 
     * @type {Visibility}
     * @memberof BasicInfo
     */
    'visibility': Visibility;
}

