/* tslint:disable */
/* eslint-disable */
/**
 * 基本情報編集API
 * ユーザーの基本情報を編集するためのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Visibility
 */
export interface Visibility {
    /**
     * 
     * @type {boolean}
     * @memberof Visibility
     */
    'name': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Visibility
     */
    'self_introduction': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Visibility
     */
    'x': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Visibility
     */
    'instagram': boolean;
}

